# Generated by Django 4.2.7 on 2023-11-25 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id_loja', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('endereco', models.CharField(max_length=50)),
                ('horario_atendimento', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_produto', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=30)),
                ('nome', models.CharField(max_length=30)),
                ('lote', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='VendeProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.FloatField()),
                ('loja', models.CharField(max_length=10)),
                ('produto', models.CharField(max_length=10)),
            ],
        ),
    ]
